### ISSUE TITLE
FTPS Not working?

### ISSUE THREAD

**Issue by ChaseGuru** [salim-lachdhaf/dartFTP#18]
Filezilla is able to connect to a machine, and I got curl working too, but I can't get connect in the library to work.

```
final ftp = FTPConnect(
  '10.22.3.185',
  port: 990,
  user: 'asdf',
  pass: 'asdfasdf',
  securityType: SecurityType.FTPS,
  timeout: 3,
);
await ftp.connect();
```

Depending on combination of settings it times out or gets a connection refused.

I didn't see a FTPS example in the lib/example folder either.  It does seem like your code attempts to do stuff for FTPS, and it's possible I'm configuring something wrong.

**Comment by ChaseGuru** [comment]
OK, I believe the library does the FTPS handshake wrong.  I'm making a PR now.

**Comment by ChaseGuru** [comment]
Fixed here:
https://github.com/salim-lachdhaf/dartFTP/pull/19

**Comment by ChaseGuru** [comment]
@salim-lachdhaf thanks for merging my code, hopefully it's helpful.

It would also be very helpful I think to note in docs somewhere that Android and iOS can't do ssl session re-use so even with my fixed code, FTPS won't work if the ftp server requires ssl session re-use.

While in the specific use case of FTPS, it increases security by ensuring it's the same party for the multiple sockets, in the context of Android/iOS it's not functionality that's provided and in terms of general networking allowing the ability to specify session parameters is considered insecure.

**Comment by rubencalje** [comment]
I think FTPS (FTP/SSL, implicit mode) is still broken. When testing with the Rebex-server, I get the following log-messages:

> I/flutter ( 7550): [2024-06-21 11:29:29.900861] Connecting...
> I/flutter ( 7550): [2024-06-21 11:29:30.098133] Connection established, waiting for welcome message...
> I/flutter ( 7550): [2024-06-21 11:29:30.406971] < FTPReply =  [code= 220, message= 220-Welcome to test.rebex.net!
> I/flutter ( 7550):     See https://test.rebex.net/ for more information and terms of use.
> I/flutter ( 7550): 220 If you don't have an account, log in as 'anonymous' or 'ftp'.]
> I/flutter ( 7550): [2024-06-21 11:29:30.407535] > PBSZ 0
> D/EGL_emulation( 7550): app_time_stats: avg=16.43ms min=8.39ms max=102.42ms count=50
> I/flutter ( 7550): [2024-06-21 11:29:30.715847] < FTPReply =  [code= 530, message= 530 Not logged in.]
> I/flutter ( 7550): [2024-06-21 11:29:30.716216] > PROT P
> I/flutter ( 7550): [2024-06-21 11:29:31.019078] < FTPReply =  [code= 530, message= 530 Not logged in.]
> I/flutter ( 7550): [2024-06-21 11:29:31.019337] > USER demo
> I/flutter ( 7550): [2024-06-21 11:29:31.328616] < FTPReply =  [code= 331, message= 331 Anonymous login OK, send your complete email address as your password.]
> I/flutter ( 7550): [2024-06-21 11:29:31.329419] > PASS password
> I/flutter ( 7550): [2024-06-21 11:29:31.637655] < FTPReply =  [code= 230, message= 230 User 'demo' logged in.]
> I/flutter ( 7550): [2024-06-21 11:29:31.639396] Connected!
> I/flutter ( 7550): [2024-06-21 11:29:31.644652] > TYPE I
> D/EGL_emulation( 7550): app_time_stats: avg=12.89ms min=4.11ms max=38.16ms count=54
> I/flutter ( 7550): [2024-06-21 11:29:31.956855] < FTPReply =  [code= 200, message= 200 TYPE set to I.]
> I/flutter ( 7550): [2024-06-21 11:29:31.983377] > PASV
> I/flutter ( 7550): [2024-06-21 11:29:32.285471] < FTPReply =  [code= 227, message= 227 Entering Passive Mode (194,108,117,16,4,13)]
> I/flutter ( 7550): [2024-06-21 11:29:32.286609] > MLSD
> I/flutter ( 7550): [2024-06-21 11:29:32.330847] < FTPReply =  [code= 150, message= 150 Opening 'BINARY' data connection.]
> I/flutter ( 7550): [2024-06-21 11:29:32.667874] < FTPReply =  [code= 226, message= 226 Transfer complete.]

So, although, the connection is established, the first commands ("PBSZ 0" and "PROT P") produce an 530-error message, stating that the user is not logged in yet.

**Comment by csga5000** [comment]
@rubencalje If your ftps server requires TLS session reuse then it is impossible to fix on Android and iOS.

This is because, for security on Android and iOS every connection gets a new key and that's all managed by Android.

For ftps, which has a separate command and data connection, it's actually important for security to use the same key so that it can be ensured that both connections are the same person.

But android and iOS didn't think of that use case I guess.

You can for example download any ftp(s) capable app of the app store and test if you can connect to your ftps server through that app.  If it works, then there may be a bug in this library.  If it does not work in any apps, there's probably a reason it doesn't work for yours.

I had to abandon my use case and move towards a different solution.

**Comment by csga5000** [comment]
If you see native java solutions online for reusing session that utilize reflection, note that they won't actually work on Android, because android actually blocks many kinds of reflection that could be used to get around their security restrictions.
